In [1]:
import numpy as np


In [2]:
# Tek boyutlu integer array
arr1 = np.array([1, 2, 3, 4, 5], dtype=int)

print("Array:", arr1)
print("Boyut (ndim):", arr1.ndim)
print("Eleman sayısı (size):", arr1.size)

Array: [1 2 3 4 5]
Boyut (ndim): 1
Eleman sayısı (size): 5


In [3]:
# İki boyutlu array
arr2d = np.array([[1, 2, 6, 7],
                  [4, 3, 9, 5]])

print("\nİki boyutlu array:")
print(arr2d)
print("Boyut (ndim):", arr2d.ndim)
print("Eleman sayısı (size):", arr2d.size)
print("Şekil (shape):", arr2d.shape)  # (satır, sütun)

# Üç boyutlu array
arr3d = np.array([[[7, 5, 14], [21, 8, 11]],
                  [[8, 6, 20], [14, 3, 9]]])

print("\nÜç boyutlu array:")
print(arr3d)
print("Boyut (ndim):", arr3d.ndim)
print("Eleman sayısı (size):", arr3d.size)
print("Şekil (shape):", arr3d.shape)  # (blok, satır, sütun)


İki boyutlu array:
[[1 2 6 7]
 [4 3 9 5]]
Boyut (ndim): 2
Eleman sayısı (size): 8
Şekil (shape): (2, 4)

Üç boyutlu array:
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut (ndim): 3
Eleman sayısı (size): 12
Şekil (shape): (2, 2, 3)


In [4]:
print("\nİki boyutlu arrayde 2 elemanı:", arr2d[0, 1])
print("İki boyutlu arrayde 7 elemanı:", arr2d[0, 3])

print("Üç boyutlu arrayde 9 elemanı:", arr3d[1, 1, 2])
print("Üç boyutlu arrayde 5 elemanı:", arr3d[0, 0, 1])


İki boyutlu arrayde 2 elemanı: 2
İki boyutlu arrayde 7 elemanı: 7
Üç boyutlu arrayde 9 elemanı: 9
Üç boyutlu arrayde 5 elemanı: 5


In [5]:
print("\nİki boyutlu arrayde 2, 6 elemanları:", arr2d[0, 1:3])
print("İki boyutlu arrayde 3, 9, 5 elemanları:", arr2d[1, 1:4])

print("Üç boyutlu arrayde 21, 8, 11 elemanları:", arr3d[0, 1, :])
print("Üç boyutlu arrayde 6, 20 elemanları:", arr3d[1, 0, 1:3])


İki boyutlu arrayde 2, 6 elemanları: [2 6]
İki boyutlu arrayde 3, 9, 5 elemanları: [3 9 5]
Üç boyutlu arrayde 21, 8, 11 elemanları: [21  8 11]
Üç boyutlu arrayde 6, 20 elemanları: [ 6 20]


In [6]:
# 5 satır 3 sütun sıfırlardan oluşan array
zeros_arr = np.zeros((5, 3), dtype=int)

# 5 satır 3 sütun birlerden oluşan array
ones_arr = np.ones((5, 3), dtype=int)

print("\nSıfırlardan oluşan array:\n", zeros_arr)
print("\nBirlerden oluşan array:\n", ones_arr)

# Satır bazında birleştirme (alt alta)
satir_birlesim = np.vstack((zeros_arr, ones_arr))
print("\nSatır bazında birleştirilmiş array:\n", satir_birlesim)

# Sütun bazında birleştirme (yan yana)
sutun_birlesim = np.hstack((zeros_arr, ones_arr))
print("\nSütun bazında birleştirilmiş array:\n", sutun_birlesim)


Sıfırlardan oluşan array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Birlerden oluşan array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Satır bazında birleştirilmiş array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sütun bazında birleştirilmiş array:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
